name: finances
description: "A personal offline-only finance tracking app that keeps your data where it belongs: locally on your device."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  decimal: ^3.2.4
  freezed_annotation: any
  objectbox: ^5.1.0
  objectbox_flutter_libs: any
  path: ^1.9.1
  path_provider: ^2.1.5
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  get_it: ^9.2.1
  equatable: ^2.0.8
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  freezed: ^3.2.3
  build_runner: ^2.10.5
  objectbox_generator: ^5.1.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

objectbox:
  output_dir:
    lib: infra/data/objectbox/gen
    test: infra/data/objectbox/gen